Repository kiosk-max-06/kiosk-max, pull requests merged in 2023-06, with the labels that each got.

#10 #5 feat : Entity 생성
  backend/src/main/java/team6/codesquad/kiosk/order/domain/Category.java
  backend/src/main/java/team6/codesquad/kiosk/order/domain/Menu.java
  backend/src/main/java/team6/codesquad/kiosk/order/domain/Option.java
  backend/src/main/java/team6/codesquad/kiosk/order/domain/Order.java
  backend/src/main/java/team6/codesquad/kiosk/order/domain/OrderMenu.java
  backend/src/main/java/team6/codesquad/kiosk/order/domain/OrderMenuOption.java
  backend/src/main/java/team6/codesquad/kiosk/order/domain/OrderStatus.java
  backend/src/main/java/team6/codesquad/kiosk/order/domain/Payment.java
  backend/src/main/java/team6/codesquad/kiosk/order/domain/Sales.java
Labels: feature, be

#11 #4 feat : schema.sql 작성 및 DB 설정
  backend/build.gradle
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
  backend/src/main/resources/schema.sql
Labels: docs, be

#14 #4 fix : 스키마 수정
  backend/src/main/resources/schema.sql
Labels: fix, be

#20 #4 feat: 스키마 수정 및 data.sql 파일 추가
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
Labels: feature, fix, be

#30 #29 chore : Swagger 적용
  backend/build.gradle
  backend/src/main/java/team6/codesquad/kiosk/order/controller/MenuController.java
  backend/src/main/java/team6/codesquad/kiosk/order/controller/OrderController.java
  backend/src/main/java/team6/codesquad/kiosk/order/repository/MenuRepository.java
  backend/src/main/java/team6/codesquad/kiosk/order/service/MenuService.java
Labels: docs, be

#36 #34 feat : Response Entity 생성
  backend/src/main/java/team6/codesquad/kiosk/order/controller/OrderController.java
  backend/src/main/java/team6/codesquad/kiosk/order/dto/response/OrderResponseDto.java
  backend/src/main/java/team6/codesquad/kiosk/order/repository/MenuRepository.java
  backend/src/main/java/team6/codesquad/kiosk/order/service/OrderService.java
  backend/src/test/java/team6/codesquad/kiosk/menu/MenuRepositoryTest.java
  backend/src/test/java/team6/codesquad/kiosk/order/repository/OrderRepositoryTest.java
Labels: feature, be

#35 #31 refactor: 메뉴 API의 Service, Repository 를 역할에 맞게 리팩터링
  backend/src/main/java/team6/codesquad/kiosk/order/repository/MenuRepository.java
  backend/src/main/java/team6/codesquad/kiosk/order/service/MenuService.java
Labels: refactoring, be
